import {
  ApplicationConfig,
  importProvidersFrom,
  provideZoneChangeDetection,
} from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { LucideAngularModule } from 'lucide-angular';
import {
  ArrowLeft,
  ArrowRight,
  Calendar,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Droplets,
  Facebook,
  Filter,
  Home,
  Instagram,
  Leaf,
  Lock,
  LogOut,
  MapPin,
  Menu,
  Minus,
  Package,
  Plus,
  Search,
  ShoppingBag,
  Sparkles,
  Star,
  Sun,
  Thermometer,
  Trash2,
  TrendingUp,
  Truck,
  Twitter,
  User,
  X,
} from 'lucide-angular/src/icons';
import { routes } from './app.routes';

const lucideIcons = LucideAngularModule.pick({
  ArrowLeft,
  ArrowRight,
  Calendar,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Droplets,
  Facebook,
  Filter,
  Home,
  Instagram,
  Leaf,
  Lock,
  LogOut,
  MapPin,
  Menu,
  Minus,
  Package,
  Plus,
  Search,
  ShoppingBag,
  Sparkles,
  Star,
  Sun,
  Thermometer,
  Trash2,
  TrendingUp,
  Truck,
  Twitter,
  User,
  X,
});

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes, withComponentInputBinding()),
    provideAnimationsAsync(),
    importProvidersFrom(lucideIcons),
  ],
};
